// ─── Indian Helpline Data ───────────────────────────────────────────────────

export const helplines = [
  {
    id: 'childline',
    name: 'CHILDLINE India',
    number: '1098',
    category: 'child-safety',
    categoryLabel: 'Child Safety',
    description:
      "India's 24/7 emergency helpline for children in need of care and protection. Free, confidential, and available across India.",
    languages: ['Hindi', 'English', 'Regional Languages'],
    available: '24/7',
    free: true,
    icon: '🛡️',
    color: 'coral',
  },
  {
    id: 'icall',
    name: 'iCall — TISS',
    number: '9152987821',
    category: 'mental-health',
    categoryLabel: 'Mental Health',
    description:
      'Free psychosocial helpline by Tata Institute of Social Sciences. Staffed by trained psychologists for counselling, guidance, and mental health support.',
    languages: ['Hindi', 'English'],
    available: 'Mon–Sat, 8 AM–10 PM',
    free: true,
    icon: '🧠',
    color: 'teal',
  },
  {
    id: 'vandrevala',
    name: 'Vandrevala Foundation',
    number: '1860-2662-345',
    category: 'mental-health',
    categoryLabel: 'Mental Health',
    description:
      '24/7 mental health support for crisis intervention, depression, anxiety, and emotional distress. Confidential and free.',
    languages: ['Hindi', 'English'],
    available: '24/7',
    free: true,
    icon: '💚',
    color: 'teal',
  },
  {
    id: 'snehi',
    name: 'SNEHI',
    number: '044-24640050',
    category: 'crisis',
    categoryLabel: 'Crisis & Suicide',
    description:
      'Suicide prevention helpline providing emotional support to those in acute distress. Empathetic, non-judgmental listening.',
    languages: ['Hindi', 'English', 'Tamil'],
    available: '24 hours',
    free: true,
    icon: '🌿',
    color: 'teal',
  },
  {
    id: 'aasra',
    name: 'AASRA',
    number: '9820466627',
    category: 'crisis',
    categoryLabel: 'Crisis & Suicide',
    description:
      'A volunteer-run crisis intervention center for people who are overwhelmed and feeling suicidal. Trained volunteers offer a compassionate ear.',
    languages: ['Hindi', 'English'],
    available: '24/7',
    free: true,
    icon: '🤝',
    color: 'amber',
  },
  {
    id: 'nimhans',
    name: 'NIMHANS Helpline',
    number: '080-46110007',
    category: 'mental-health',
    categoryLabel: 'Mental Health',
    description:
      'National Institute of Mental Health and Neuro Sciences — tele-counselling and guidance for mental health emergencies.',
    languages: ['Hindi', 'English', 'Kannada'],
    available: '24/7',
    free: true,
    icon: '🏥',
    color: 'teal',
  },
  {
    id: 'womens-helpline',
    name: "Women's Helpline",
    number: '181',
    category: 'women-safety',
    categoryLabel: "Women's Safety",
    description:
      "National Women's Helpline for harassment, abuse, domestic violence, and safety concerns. Connects you to local women's protection officers.",
    languages: ['Hindi', 'English', 'Regional'],
    available: '24/7',
    free: true,
    icon: '🌸',
    color: 'coral',
  },
  {
    id: 'police',
    name: 'Police Emergency',
    number: '100',
    category: 'emergency',
    categoryLabel: 'Emergency',
    description:
      'National emergency number for immediate police assistance. Use if you or someone is in immediate physical danger.',
    languages: ['All Languages'],
    available: '24/7',
    free: true,
    icon: '🚨',
    color: 'coral',
  },
  {
    id: 'cyber-crime',
    name: 'Cyber Crime Helpline',
    number: '1930',
    category: 'cyber',
    categoryLabel: 'Cybercrime & Online Safety',
    description:
      'Report cyberbullying, online harassment, morphed images, and sextortion. Dedicated helpline by Ministry of Home Affairs.',
    languages: ['Hindi', 'English'],
    available: '24/7',
    free: true,
    icon: '💻',
    color: 'amber',
  },
  {
    id: 'mann-talk',
    name: 'Mann Talks',
    number: '8686139139',
    category: 'mental-health',
    categoryLabel: 'Mental Health',
    description:
      'Mental health helpline specifically for young people and students. Peer support + professional counselors for anxiety, stress, and burnout.',
    languages: ['Hindi', 'English'],
    available: 'Mon–Sun, 9 AM–9 PM',
    free: true,
    icon: '🌻',
    color: 'amber',
  },
  {
    id: 'kiran',
    name: 'KIRAN Mental Health',
    number: '1800-599-0019',
    category: 'mental-health',
    categoryLabel: 'Mental Health',
    description:
      'Government of India free 24/7 mental health rehabilitation helpline. First responders for psychological trauma, distress, and mental illness.',
    languages: ['Hindi', 'English', '13 Regional Languages'],
    available: '24/7',
    free: true,
    icon: '☀️',
    color: 'teal',
  },
  {
    id: 'ncpcr',
    name: 'NCPCR Complaint',
    number: '1800-121-2830',
    category: 'child-safety',
    categoryLabel: 'Child Safety',
    description:
      'National Commission for Protection of Child Rights — for reporting abuse, exploitation, school harassment, and rights violations.',
    languages: ['Hindi', 'English'],
    available: 'Mon–Fri, 9 AM–5 PM',
    free: true,
    icon: '⚖️',
    color: 'coral',
  },
];

export const categories = [
  { id: 'all', label: 'All Helplines' },
  { id: 'mental-health', label: 'Mental Health' },
  { id: 'crisis', label: 'Crisis & Suicide' },
  { id: 'child-safety', label: 'Child Safety' },
  { id: 'women-safety', label: "Women's Safety" },
  { id: 'cyber', label: 'Cybercrime' },
  { id: 'emergency', label: 'Emergency' },
];
