// ─── Resources Data ──────────────────────────────────────────────────────────

export const resources = [
  {
    id: 'anxiety',
    title: 'Understanding Anxiety',
    emoji: '😰',
    tag: 'Mental Health',
    tagColor: 'teal',
    summary: 'Feeling constantly worried, nervous, or scared? You are not broken — your brain is just trying to protect you.',
    whatItIs: `Anxiety is your body's natural alarm system. When you feel threatened — by a test, a social situation, or even just a thought — your body releases stress hormones. This is normal. But when the alarm goes off too often or too strongly, it becomes anxiety.

In India, anxiety is extremely common among teens, especially with board exam pressure, parental expectations, and social comparisons on Instagram.`,
    signs: [
      'Heart beating faster than usual for no clear reason',
      'Sweating, shaking, or feeling dizzy',
      'Stomach aches or nausea before events',
      'Avoiding situations you used to enjoy',
      'Trouble sleeping because your mind won\'t stop',
      'Feeling like something terrible is about to happen',
      'Difficulty concentrating in class or conversations',
    ],
    whatToDo: [
      '**Breathe: 4-7-8 method** — Inhale for 4 counts, hold for 7, exhale for 8. This calms your nervous system within minutes.',
      '**Ground yourself** — Name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste.',
      '**Write it out** — Dump all your worries onto paper. Then ask yourself: "Is this thought 100% true?"',
      '**Talk to someone** — A trusted friend, a counselor, or even Aanya on this platform.',
      '**Reduce caffeine** — Chai, coffee, and energy drinks make anxiety worse.',
      '**Move your body** — 20 minutes of walking can reduce anxiety as much as some medications.',
    ],
    doNot: [
      'Don\'t bottle it up and pretend you\'re fine',
      'Don\'t use social media scrolling to escape — it makes it worse',
      'Don\'t compare yourself to others who "seem" fine',
      'Don\'t avoid everything that scares you — avoidance grows anxiety',
    ],
    whoToCall: 'iCall (9152987821) | KIRAN (1800-599-0019)',
    readTime: '5 min',
    color: '#14b8a6',
  },
  {
    id: 'depression',
    title: 'When Everything Feels Dark',
    emoji: '🌧️',
    tag: 'Mental Health',
    tagColor: 'teal',
    summary: 'Depression is not sadness. It\'s a heavy emptiness. And it is absolutely treatable.',
    whatItIs: `Depression is not just "feeling sad." It's a clinical condition that changes how you think, feel, and function every day for weeks. It's not weakness. It's not drama. It's not attention-seeking.

Many teens in India suffer in silence because of the stigma around mental health. But depression is as real as a broken leg — and just as treatable.`,
    signs: [
      'Feeling empty, hopeless, or numb — not just sad',
      'No interest in things you used to love (games, friends, food)',
      'Sleeping too much or not at all',
      'Feeling worthless or like you\'re a burden',
      'Changes in appetite — eating much more or much less',
      'Difficulty doing even basic tasks',
      'Thoughts of hurting yourself or not wanting to exist',
    ],
    whatToDo: [
      '**Tell someone today** — This is the most important step. A parent, teacher, counselor, or anyone you trust.',
      '**Talk to a professional** — Depression responds very well to therapy and sometimes medication. This is not weakness.',
      '**Tiny steps matter** — Don\'t try to fix everything. Just shower. Just eat one meal. Just step outside for 5 minutes.',
      '**Sunlight and movement** — Natural light and gentle exercise are scientifically proven to lift mood.',
      '**Limit isolation** — Depression wants you to be alone. Fight that. Text one person today.',
    ],
    doNot: [
      'Don\'t tell yourself to "just be grateful" or "think positive"',
      'Don\'t self-medicate with alcohol or substances',
      'Don\'t wait for it to pass on its own for more than 2 weeks',
      'Don\'t be alone with very dark thoughts',
    ],
    whoToCall: 'AASRA (9820466627) | Vandrevala (1860-2662-345) | NIMHANS (080-46110007)',
    readTime: '6 min',
    color: '#0d9488',
    urgent: true,
  },
  {
    id: 'academic-burnout',
    title: 'Academic & Coaching Burnout',
    emoji: '📚',
    tag: 'Academic Stress',
    tagColor: 'amber',
    summary: 'If you\'re studying 14 hours a day and still feel like you\'re failing, you are not lazy — you are burnt out.',
    whatItIs: `In India, the pressure of boards, JEE, NEET, and parental expectations can push teens to their absolute limits. Kota syndrome is real. Many students who move to coaching cities lose all sense of identity outside of marks.

Burnout is when your mind, body, and heart completely run out of fuel from prolonged stress. It's not laziness — it's a biological response to being pushed too hard for too long.`,
    signs: [
      'Studying for hours but retaining nothing',
      'Feeling exhausted even after sleeping',
      'Dread or panic every time you open a textbook',
      'Crying before exams or during study sessions',
      'Feeling like you are "not smart enough" no matter how hard you try',
      'Physical symptoms: headaches, stomachaches, hair loss',
      'Losing interest in literally everything except studying',
    ],
    whatToDo: [
      '**Take a genuine break** — Not guilty scrolling. A walk, a hobby, anything unrelated to marks.',
      '**Talk to your parents honestly** — They want the best for you, but they may not know how you\'re suffering.',
      '**Restructure your schedule** — You cannot study 12+ hours effectively. Science says 4-5 deep focus hours beats 14 distracted hours.',
      '**Reconnect with something you love** — Music, drawing, cooking, cricket. You are more than your rank.',
      '**Speak to a counselor** — School counselors, iCall, and Mann Talks specialize in academic stress.',
    ],
    doNot: [
      'Don\'t compare your hours of study to classmates',
      'Don\'t sacrifice sleep — sleep is when your brain consolidates memory',
      'Don\'t believe that your worth equals your rank',
      'Don\'t disappear from family and friends to study more',
    ],
    whoToCall: 'iCall (9152987821) | Mann Talks (8686139139)',
    readTime: '6 min',
    color: '#f59e0b',
  },
  {
    id: 'harassment-teacher',
    title: 'Harassment by a Teacher',
    emoji: '🏫',
    tag: 'Harassment',
    tagColor: 'coral',
    summary: 'No teacher has the right to humiliate, touch inappropriately, or threaten you. Ever.',
    whatItIs: `Teacher harassment in India includes public humiliation in class, physical punishment (now illegal), sexual remarks or touching, pressuring students for private tuitions, and using grades as weapons.

Many students don't report it because they fear no one will believe them, their grades will drop, or they'll be labelled a troublemaker. But your safety comes before any grade.`,
    signs: [
      'Feeling dread or nausea before a particular class',
      'Being singled out for humiliation in front of classmates',
      'Inappropriate touching — however minor it seems',
      'Sexual jokes, comments, or looks directed at you',
      'Being threatened with low grades for not complying',
      'Feeling scared, ashamed, or confused after interactions with this teacher',
    ],
    whatToDo: [
      '**Write it down** — Date, time, what happened, any witnesses. Documentation is powerful.',
      '**Tell a trusted adult today** — A different teacher, school counselor, parent, or relative.',
      '**Report to the principal in writing** — Put your complaint in writing so there\'s a record.',
      '**Contact NCPCR** — The National Commission for Protection of Child Rights handles school harassment (1800-121-2830).',
      '**You are NOT overreacting** — If something felt wrong, it probably was wrong.',
    ],
    doNot: [
      'Don\'t keep it secret out of shame — the shame belongs to them, not you',
      'Don\'t confront the teacher alone',
      'Don\'t let it continue because you\'re scared of your grades',
      'Don\'t convince yourself it was "not a big deal"',
    ],
    whoToCall: 'CHILDLINE (1098) | NCPCR (1800-121-2830) | Police (100)',
    readTime: '5 min',
    color: '#f97316',
    urgent: true,
  },
  {
    id: 'family-pressure',
    title: 'Toxic Family Dynamics',
    emoji: '🏠',
    tag: 'Family',
    tagColor: 'amber',
    summary: 'Family is supposed to be your safe place. When it isn\'t, that pain is real — and you deserve support.',
    whatItIs: `Toxic family dynamics include constant criticism, comparison to siblings or cousins, controlling behaviour, emotional neglect, verbal abuse ("you\'re useless"), and physical punishment.

In Indian families, expressing pain or setting boundaries is often labelled as "disrespect." But your emotional needs are just as important as anyone else's.`,
    signs: [
      'Feeling like you can never do anything right',
      'Walking on eggshells around a parent or family member',
      'Being constantly compared to others ("look at your cousin")',
      'Your feelings being dismissed: "stop being dramatic"',
      'Physical punishment or being hit',
      'Feeling safer at school or a friend\'s home than your own',
      'Hiding parts of yourself to avoid conflict',
    ],
    whatToDo: [
      '**Find one safe adult** — A relative, teacher, school counselor, or friend\'s parent who you trust.',
      '**Know your boundaries** — Calmly (when everyone is calm) say "It hurts me when..."',
      '**Build your support network outside home** — Close friends, teachers, community.',
      '**Write in your journal** — Processing emotions privately protects your mental health.',
      '**Seek counseling** — Family counselors can mediate. iCall offers family counseling too.',
    ],
    doNot: [
      'Don\'t internalize criticism as truth about who you are',
      'Don\'t retaliate with anger — it rarely helps',
      'Don\'t suffer completely alone',
      'Don\'t put off seeking help because you think it\'ll get better on its own',
    ],
    whoToCall: 'iCall (9152987821) | CHILDLINE (1098) | KIRAN (1800-599-0019)',
    readTime: '5 min',
    color: '#f59e0b',
  },
  {
    id: 'peer-pressure',
    title: 'Peer Pressure & Toxic Friendships',
    emoji: '👥',
    tag: 'Friendships',
    tagColor: 'teal',
    summary: 'Real friends don\'t pressure you to do things that make you uncomfortable. Full stop.',
    whatItIs: `Peer pressure ranges from subtle ("you\'re so boring") to direct ("just try it once"). Toxic friendships control you through guilt, manipulation, exclusion, and humiliation.

Online bullying and group chats have made peer pressure 24/7. You can\'t escape it just by going home anymore.`,
    signs: [
      'Feeling like you need to act differently around certain friends',
      'Being pressured to drink, smoke, vape, or try substances',
      'Friends who embarrass or mock you "as a joke"',
      'Being excluded from groups as punishment',
      'Sharing your secrets being used against you',
      'Feeling drained, anxious, or bad about yourself after hanging out',
      'Screenshots of your chats being shared without consent',
    ],
    whatToDo: [
      '**Trust your gut** — If something feels wrong, it is. Your instincts are data.',
      '**Practice saying no** — "I\'m not into that" is a complete sentence. You don\'t need to explain.',
      '**Distance yourself gradually** — You don\'t have to make a dramatic exit. Slowly spend less time.',
      '**Find your real people** — Join a club, sport, or online community where you feel genuinely welcome.',
      '**Block and report cyberbullying** — Save screenshots and report to the platform and police if needed.',
    ],
    doNot: [
      'Don\'t sacrifice your values to fit in',
      'Don\'t enable others\' toxic behaviour by staying silent',
      'Don\'t be the person who does the same thing to others',
      'Don\'t share anyone\'s private photos, messages, or secrets',
    ],
    whoToCall: 'iCall (9152987821) | Cyber Crime (1930) | Vandrevala (1860-2662-345)',
    readTime: '5 min',
    color: '#14b8a6',
  },
  {
    id: 'sexual-harassment',
    title: 'Sexual Harassment & Abuse',
    emoji: '⚠️',
    tag: 'Safety',
    tagColor: 'coral',
    summary: 'No one has the right to touch you, speak to you sexually, or send you inappropriate content without consent.',
    whatItIs: `Sexual harassment includes unwanted touching, sexually explicit messages or calls, being sent or shown inappropriate images, being photographed without consent, and sexual remarks or threats.

It can happen from peers, seniors, teachers, relatives, or online strangers. It is NEVER your fault, regardless of what you wore, said, or did.`,
    signs: [
      'Someone touching you in ways that feel wrong',
      'Receiving sexual messages or images you didn\'t ask for',
      'Being pressured to share intimate photos',
      'Someone exposing themselves to you',
      'Feeling watched, followed, or monitored',
      'Threats to share your photos or information',
    ],
    whatToDo: [
      '**This is not your fault. Not now. Not ever.**',
      '**Tell someone you trust immediately** — parent, relative, teacher, counselor.',
      '**Save evidence** — Screenshots, messages, call logs. Don\'t delete anything.',
      '**Report to police or CHILDLINE** — Sexual harassment of a minor is a criminal offence under POCSO.',
      '**Seek counseling** — Trauma needs professional support. AASRA and Vandrevala have trained counselors.',
    ],
    doNot: [
      'Don\'t blame yourself for any reason',
      'Don\'t stay silent because of fear or shame',
      'Don\'t meet the person alone again',
      'Don\'t delete evidence, even if it\'s disturbing to have',
    ],
    whoToCall: 'CHILDLINE (1098) | Police (100) | Women\'s Helpline (181) | Cyber Crime (1930)',
    readTime: '4 min',
    color: '#f97316',
    urgent: true,
  },
  {
    id: 'online-safety',
    title: 'Online Bullying & Digital Safety',
    emoji: '📱',
    tag: 'Digital Safety',
    tagColor: 'amber',
    summary: 'What happens online is real. Cyberbullying hurts just as much as physical bullying — and it\'s 24/7.',
    whatItIs: `Cyberbullying includes posting mean comments, creating fake profiles, sharing private photos/videos, excluding from online groups, and spreading rumours online.

In India, many teens don\'t report it because they fear phones will be taken away or they\'ll be blamed. But you deserve online safety as much as physical safety.`,
    signs: [
      'Receiving threatening, embarrassing, or hurtful messages',
      'Being posted about on social media without your consent',
      'Someone pretending to be you online',
      'Group chats used to mock or exclude you',
      'Private photos being shared without permission',
      'Feeling afraid to use your phone or social media',
    ],
    whatToDo: [
      '**Block the person** — On every platform.',
      '**Screenshot everything first** — Document before blocking.',
      '**Report to the platform** — Instagram, WhatsApp, Snapchat all have abuse report features.',
      '**Tell a trusted adult** — Show them the evidence.',
      '**Report to Cyber Crime Helpline** — 1930 or cybercrime.gov.in',
      '**Take a social media break** — You don\'t have to be reachable 24/7.',
    ],
    doNot: [
      'Don\'t respond to bullies online — it escalates things',
      'Don\'t share private images of yourself with anyone online',
      'Don\'t suffer alone or "toughen up"',
      'Don\'t delete your evidence before reporting',
    ],
    whoToCall: 'Cyber Crime (1930) | CHILDLINE (1098) | iCall (9152987821)',
    readTime: '4 min',
    color: '#f59e0b',
  },
];

export const resourceCategories = [
  { id: 'all', label: 'All Resources' },
  { id: 'Mental Health', label: '🧠 Mental Health' },
  { id: 'Academic Stress', label: '📚 Academic Stress' },
  { id: 'Harassment', label: '⚠️ Harassment' },
  { id: 'Family', label: '🏠 Family' },
  { id: 'Friendships', label: '👥 Friendships' },
  { id: 'Safety', label: '🛡️ Safety' },
  { id: 'Digital Safety', label: '📱 Digital Safety' },
];
